# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(229, 167)
        Form.setAccessibleName("")
        self.login_button = QtWidgets.QPushButton(Form)
        self.login_button.setGeometry(QtCore.QRect(70, 110, 75, 23))
        self.login_button.setObjectName("login_button")
        self.id_label = QtWidgets.QLabel(Form)
        self.id_label.setGeometry(QtCore.QRect(10, 20, 56, 21))
        self.id_label.setAlignment(QtCore.Qt.AlignCenter)
        self.id_label.setObjectName("id_label")
        self.id_line = QtWidgets.QLineEdit(Form)
        self.id_line.setGeometry(QtCore.QRect(80, 20, 113, 20))
        self.id_line.setObjectName("id_line")
        self.pw_label = QtWidgets.QLabel(Form)
        self.pw_label.setGeometry(QtCore.QRect(10, 60, 56, 21))
        self.pw_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pw_label.setObjectName("pw_label")
        self.pw_line = QtWidgets.QLineEdit(Form)
        self.pw_line.setGeometry(QtCore.QRect(80, 60, 113, 20))
        self.pw_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pw_line.setObjectName("pw_line")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Jcro"))
        self.login_button.setText(_translate("Form", "login"))
        self.id_label.setText(_translate("Form", "ID"))
        self.pw_label.setText(_translate("Form", "PW"))

    def login(self):
        print(self.id_line.text())
        print(self.pw_line.text())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
